#!/bin/bash

echo "enola testing"
echo "build with <3"
echo "--derune labs--"

OS=$(uname -s)
PACKAGE_MANAGER=""
GOOGLETEST_FOLDER="googletest"
BUILD_DIR="build"

handle_error() {
  echo "Error: $1"
  exit 1
}

if [[ "$OS" == "Linux" ]]; then
  if command -v apt-get >/dev/null 2>&1; then
    PACKAGE_MANAGER="apt-get"
  elif command -v pacman >/dev/null 2>&1; then
    # TODO: for future use
    PACKAGE_MANAGER="pacman"
  else
    handle_error "not supported package"
  fi
elif [[ "$OS" == "Darwin" ]]; then
  PACKAGE_MANAGER="brew"
else
  handle_error "not supporteed operating system"
fi

if [[ "$PACKAGE_MANAGER" == "apt-get" ]]; then
  if !dpkg -l | grep libgtest-dev; then
    sudo apt-get install libgtest-dev cmake
  fi
fi

echo "intializing google test"
if [ -d "$GOOGLETEST_FOLDER" ]; then
  echo "already installed"
else
  git clone https://github.com/google/googletest.git -b release-1.12.1
fi

if [ -d "build" ]; then
  cd build
else
  mkdir build
  cd build
fi

cmake ..
make
./test/run_tests
