name: Test linux base

on: [push, pull_request]

jobs:
  build-and-testing:
    runs-on: ${{ matrix.os }}
    startegy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: verify enola test
        run: |
          chmod +x ./test/run_test
          ls -l ./test/run_test

      - name: build and test
        run: |
          ./test/run_test
        env:
          TEST_ENV_VAR: "enola_test_env"
