name: Test linux base

on: [push, pull_request]

jobs:
  build-and-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build and test
        run: |
          g++ --version
          cd test
          chmod +x ./test/run_test
          ./test/run_test
