name: Test linux base

on: [push, pull_request]

jobs:
  build-and-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: opencl ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev opencl-headers

      - name: check opencl
        run: |
          ls /usr/include/CL || ls /usr/local/include/CL

      - name: verify enola test
        run: |
          chmod +x ./test/run_test
          ls -l ./test/run_test

      - name: build and test
        run: |
          ./test/run_test
        env:
          TEST_ENV_VAR: "enola_test_env"
